# JVM / memory
org.gradle.jvmargs=-Xmx4096m -XX:MaxMetaspaceSize=1024m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8 -XX:+UseParallelGC

# Build performance
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configureondemand=true
org.gradle.configuration-cache=true
org.gradle.configuration-cache.problems=warn
org.gradle.daemon=true
org.gradle.vfs.watch=true

# Kotlin
kotlin.code.style=official
kotlin.incremental=true
kotlin.caching.enabled=true
kotlin.compiler.execution.strategy=in-process

# Android
android.useAndroidX=true
android.nonTransitiveRClass=true
android.nonFinalResIds=true
android.enableJetifier=false

# AGP / R8 speed helpers
android.defaults.buildfeatures.buildconfig=true
android.suppressUnsupportedOptionWarnings=true
